### ISSUE TITLE
Videos not download on browser

### ISSUE THREAD

**Issue by siati38** [puemos/hls-downloader-web-extension#78] opened 2020-04-24 20:37 UTC
Since the extension was updated, videos downloaded for example from dmax, are downloaded to the extension but then never downloaded via the browser.

**Comment by puemos** [comment] 2020-04-24 21:20
https://it.dplay.com/dmax/highway-security-spagna/stagione-1-episodio-13/ works for me.
can you please share your OS/Browser?

**Comment by siati38** [comment] 2020-04-24 21:43
I use Windows 10/Chrome, can you try download "https://es.dplay.com/dmax/como-el-clima-cambio-la-historia/temporada-1-episodio-1/"?

**Comment by puemos** [comment] 2020-04-24 21:45
No, because it's protected

**Comment by artik00** [comment] 2020-04-24 22:24
Have the same issue, with videos originating from Open University, the download used to work in the previous version.

**Comment by siati38** [comment] 2020-04-24 22:30
I am trying to download other caps and they all download with .ts extension that I cannot reproduce with vlc

**Comment by puemos** [comment] 2020-04-24 22:59
found the problem, fixed on v2.1.1, you can download the zip file or wait for chrome store the publish the update, firefox will probably release it in a few hours.
thanks for helping me to identify the bug.

**Closed by puemos** 2020-04-24 22:59 UTC
Labels: bug

**Comment by vitorsouzas0** [comment] 2020-04-24 23:03
Good evening. I am having the same problem with version 2.0.0, I am able to download, but does not reproduce

**Comment by puemos** [comment] 2020-04-24 23:18
Solved and **pending review** on chrome
Solved and **released** on firefox: https://addons.mozilla.org/en-US/firefox/addon/hls-downloader/
