### ISSUE TITLE
Impossible to download video - Prohibition road sign on the download button

### ISSUE THREAD

**Issue by zigune** [puemos/hls-downloader-web-extension#95] opened 2020-05-11 14:47 UTC
After downloading the video, when the percent arrives at 100%, the download button has a prohibition road sign when we put the mouse on it... We were never asked for a download location....

**Comment by ahmtaras** [comment] 2020-05-11 20:16
Agree, high resolution videos do not download.

**Comment by puemos** [comment] 2020-05-12 08:59
Hey! can you please share a link to the stream?

**Comment by zigune** [comment] 2020-05-12 13:14
> Hey! can you please share a link to the stream?

It's not high resolution... I can't share the link because the page to access it is password protected...

**Comment by ahmtaras** [comment] 2020-05-12 21:51
@puemos 
Since the link is encrypted, I cannot share the stream source.
There is a situation like this when we try to download large files.
No problem, I believe it will be fixed. For now, I get the stream source from your vehicle and download with "jdownloader" or "ffmpeg".

**Comment by dosiecki** [comment] 2020-05-17 22:19
I can confirm this has been happenign to me since the last update, too.  I can see lots of quality options for videos, and they smoothly go from 0%-100%, but then at 100% the button to save the file gets the "disabled" style and nothing can be done.

Here's one example link that does it for me (lemme know if it expires and you need more - seems to happen with most twitch streams now):

https://www.twitch.tv/videos/622891737

**Comment by gitdev-bash** [comment] 2020-05-24 20:15
can't download the streams need fix

**Comment by puemos** [comment] 2020-06-08 10:01
First, thanks for taking the time to comment @dosiecki @ahmtaras @zigune @gitdev-bash 
Second, It seems like the issue is related to the new chrome versions, I will try to use [FileSystem](https://developer.mozilla.org/en-US/docs/Web/API/FileSystem) which will take some time to develop.

**Comment by mjccox** [comment] 2020-08-14 21:49
This is happening to me on firefox.

**Comment by puemos** [comment] 2020-08-20 22:59
Work in progress #132

**Closed by puemos** 2020-08-20 22:59 UTC
Labels: bug
